### PR TITLE
Adding an optional onDismiss callback option

### PR DESCRIPTION
**Pull request by chrismbarr**

### CODE REVIEW

**Comment by tameraydin** [comment]
Hi @chrismbarr, thanks for the PR!
I can merge but I didn't fully get the motivation, you already have access to the message detail -which you pass as argument on callback- at the moment you trigger dismiss. Can you explain your use case a bit?

**Comment by chrismbarr** [comment]
In my app I'm using ngToast to display error messages generated by the server.  Occasionally if there's a bad error, the exact same error message might pop up more than once.  I am trying to find a way to prevent the exact same error from displaying on the screen more than once, so I'm keeping a local array of the error text and checking if the new error is in there or not before I pop up the toast.  When it gets dismissed, I remove it from the array.

_FYI: The project uses TypeScript, not plain JS!_
``` TypeScript
var errors = [];
eventRegistry.hook(ServerEvents.OnError,(resp: any) => {
	var errorContent = "<h4>Error!</h4><pre class='pre-scrollable'>" + resp + "</pre>";
	
	//If not already in the array, continue!
	if (errors.indexOf(errorContent) === -1) {
		errors.push(errorContent);

		$rootScope.$apply(() => {
			ngToast.create({
				content: errorContent,
				className: "danger",
				dismissButton: true,
				dismissOnClick: false,
				dismissOnTimeout: false,
				onDismiss: (msg: IngToastOptions) => {
					//Remove from the errors array
					errors.splice(_.indexOf(errors, msg.content), 1);
				}
			});
		});
	}
});
```

Is there an easier way to accomplish what I'm wanting to do here?

**Comment by tameraydin** [comment]
I think there is. Check the following out (written roughly):

``` TypeScript
var errors = [];
eventRegistry.hook(ServerEvents.OnError,(resp: any) => {
	var errorContent = "<h4>Error!</h4><pre class='pre-scrollable'>" + resp + "</pre>";
	
	if (!(_.find(ngToast.messages, {'content': errorContent})) { // or a similar function to https://lodash.com/docs#find
		$rootScope.$apply(() => {
			ngToast.create({
				content: errorContent,
				className: "danger",
				dismissButton: true,
				dismissOnClick: false,
				dismissOnTimeout: false
			});
		});
	}
});
```

**Comment by levithomason** [comment]
I believe we should think about the future handling of events in ngToast at this point.  We may be setting a precedence that ngToast handles all events with callbacks.

There are a number of patterns for this case; callbacks, events, and promises come to mind.  @tameraydin what are your thoughts on patterns for events in angular?

Here is my take, today.

**Callbacks**
In the microuniverse I live in, it seems callbacks are on their way out as a somewhat anitquated pattern bringing up memories of "[call back hell](http://callbackhell.com/)".  I think they should be avoided at all costs, where possible.  If completely necessary, use of something like [async](https://github.com/caolan/async) to help manage them.

**Promises**
As we know, [promise](https://docs.angularjs.org/api/ng/service/$q) pattern was developed to help solve the async issue and callback hell.  I can see it used at least one way here.  The `create()` method could return a promise that resolves with the message on dismiss.

**Events**
I also think angular's event broadcasting system is a good fit here.  Something like `$rootScope.$broadcast(ngToast:<eventName>, <messageObject>)` would allow you to hook into events from anywhere in your app and avoid the callback hell.  Also, with this pattern we could have separate events for `create()` and `dismiss()` where as the promise pattern would be a little more convulted since we can only pass one object to the resolve (doesn't really make sense to reject a message promise).

--

Lastly, this kind of makes me consider the message stack and whether or not there should be an event system there, along with or beside some kind of history.  Getting a little broad here though...

What's your view on async operations, events, and architecture in ngToast?

**Comment by chrismbarr** [comment]
@tameraydin ah ok, thank you!  That is much simpler, I didn't realize that I was able to get a list of all the messages like that.

**Comment by tameraydin** [comment]
@chrismbarr great! np

**Comment by tameraydin** [comment]
@levithomason there are already few nice & more complex angular-toast libraries that provide such event/callback functionality out there, so I don't think it is worth for us to spend more time and effort on that. I plan to keep it as it is now, simple & small as possible, unless we see lack of a necessary or really-wanted functionality.. Otherwise yes, maybe it could be written better by considering one of these architectures you mentioned.

**Comment by levithomason** [comment]
Agreed.  I like small and focused.

**Pull request closed without merging**
