### PR TITLE
Animation Options

### PR DESCRIPTION
**Pull request by levithomason**
This PR is not ready for merge, yet.  But it is far enough along to start to get some feedback on.  Are we missing anything else for the lists below?

Items remaining:
- [x] update docs to include separate animation setup instructions
- [x] Use autoprefixer for browser support
- [x] Separate animation css from base css
- [x] Add slide in/out animation
- [x] Remove ngAnimate dependency
- [x] Add animation config option

Other items done:
- Added `grunt watch`
- Added `index.html` for ease of development

### CODE REVIEW

**Comment by tameraydin** [comment]
Great work, Levi! I will try to look at it in detail as soon as find a chance.

**Comment by levithomason** [comment]
Sounds good.   I haven't gone through and cleaned up yet. I plan to annotate the changes with PR comments to make review a little easier when u get time as well.

**Comment by tameraydin** [comment]
I was just exploring the source and the demo page, I must say it is pretty impressive and exciting! And slide animations looks pretty cool with toasts!

Also we were really lack of such a demo page that we can experiment on and that ``watch`` process of course, so these implementations will be pretty helpful for further improvements as well. After you are done with it, maybe we can also include that experiment page into the github page.

What do we need still? Are you going to be adding more animations or just left some cleanup? I look forward to merge this once it is done and make a new release.

**Comment by levithomason** [comment]
Thanks for the positive feedback.

I'd like to add animation setup instructions then clean up and merge it. I figure the two animations we have are great and they give a pattern for contributing more. 

I was also thinking the test page would work well for the github branch.

I may get some time for this tomorrow.

**Comment by levithomason** [comment]
Ok,  I added a `classes` option and renamed `className` to `alertClass`.  The `classes` option is applied to the `<li>` element.  So, one should be able to use any css animation library like so:

```css
.ng-toast__message.<my-class>.enter {
  // same for enter.active, leave, etc.
}
```

What do you think about this option?

**Comment by tameraydin** [comment]
Let's don't change ``className`` one more time, instead we can leave it as it is and use ``animationClasses`` for animation classes. It will be pretty self-explanatory I think :)

**Comment by levithomason** [comment]
You're right, it is not good to change the `className` so soon again.  What if we call the `animationClasses` option `additionalClasses`?  Since, it is technically any classes you would like to add to the message.  It doesn't necessarily have anything to do with animations, unless you want to use it that way.  The relevant template snippet:

```html
<li class="ng-toast__message {{message.additionalClasses}}">
```

Let me know what you'd like to do and we'll get it going.

**Comment by tameraydin** [comment]
any of them works I think, let's go with ``additionalClasses`` then :+1:

**Comment by levithomason** [comment]
OK, I've added the options and updated the readme with animation setup intsructions.

I also tested it out with animate.css, it was super easy and pretty cool!  Let me know if you see anyhitng you'd like changed, otherwise, it should be ready for merge :)

**Comment by tameraydin** [comment]
Great work, I will give it a final look and hopefully will merge it within this week!

**Comment by slacktracer** [comment]
@levithomason 
Hi! Sorry to bother but is there any demo using animate.css? I followed the instructions as written but it's not working. Perhaps I'm missing something but...
Anyway, if by any chance you have a fiddle or something would be really great!
Thanks. I'll keep trying tomorrow...

**Comment by levithomason** [comment]
@slacktracer I successfully tested animate.css on my local machine when I wrote the instructions. If you recreate the issue on [plunker](plnkr.co), I'd be happy to help debug.

**Comment by slacktracer** [comment]
@levithomason 
Fair enough! =)
Thank you very much. I'll get to it soon.

**Comment by levithomason** [comment]
I couldn't resist putting one together, will let you know.

**Comment by levithomason** [comment]
Working plunker [here](http://plnkr.co/edit/wglAvsCuTLLykLNqVGwU).

Things that tripped me up:

1. Don't forget vendor prefixes:

    ```css
    .my-animation.ng-enter {
        -webkit-animation: flipInY 1s;
        -moz-animation: flipInY 1s;
        animation: flipInY 1s;
    }
    .my-animation.ng-leave {
        -webkit-animation: flipOutY 1s;
        -moz-animation: flipOutY 1s;
        animation: flipOutY 1s;
    }
    ```

2. Either I am confused, or plunker is not correctly loading local css files with animation name references.  Replacing the css file with an inline `<style>` tag did the trick.

Hope this helps.  Sorry for being short previously!

**Comment by slacktracer** [comment]
Hi, @levithomason 

It worked like a charm. It was really nice of you to produce that plunker. Thank you very much, sir!
I missed the vendor-prefixes. What a rookie mistake... =(

But I forgave myself already. =P

I tested it with inline css first (as in the plunker) and then inside my css file. Everything worked just fine.

Also, no need to be sorry. You're very helpful and polite both times. I'm convinced you're a really nice guy. =)

This project is awesome and your work here is great. Thanks again and again.

**Pull request merged**
