### PR TITLE
Internet Explorer 8 Support (ie8)

### PR DESCRIPTION
**Pull request by eknowles**
Hello!

I've been using ngToast in production fore the last 6 months and it's been great. However in its current state it doesn't show the toast content in IE8 (a big requirement for many people still). This is due to angular sanitize not marking the content as trustworthy.

I've had to make two main changes.
- Changing any remaining directives in the templates from an element to attribute
  Example `'<toast-message ng-repeat...` to `'<div toast-message ng-repeat...`
  This allows IE to recognise the element.
- Mark message content as safe by using `scope.message.content = $sce.trustAsHtml(scope.message.content);` inside the directive.

To test this out I built a simple example app and included it in the PR.
http://eknowles.com/testform/testToast/index.html

Below is a screenshot of the PR working in IE8 on Windows 10.

screen shot 2015-05-14 at 16 39 44

Let me know if you have any questions :)

### CODE REVIEW

**Comment by levithomason** [comment]
Hi @eknowles, I scanned through the commits though not thoroughly.

One note, setting the directive option `replace: true` should solve your first issue without having to change the element to an attribute.

Did you mean to commit the example page along with this PR?  There is a index.html page already and also a demo site.  I don't think we'd want to add more example pages.  Though we may want to consolidate them.

**Comment by eknowles** [comment]
@levithomason I can test `replace: true` out, if it works I'll make that change. Why would replace be a better option?

I included that example as an light alternative that would work in all browsers, currently the index.html does require to be run locally and needs the bower dependents, one of which being Angular 1.3 which doesn't support IE8.

The example site I've got includes in it's `lib/` all the requirements and can be run offline if needs be. If it's helpful I can remove this and put it on divshot.io?

**Comment by levithomason** [comment]
@eknowles when the replace flag is set to true, the custom directive element is replaced with the directives template.  So, the final rendered DOM has only native HTML elements present.

Example, if we had a template: `<my-directive content="Hello World!"></my-directive>`
And a directive template like so: `<div>{{ content }}</div>`
The rendered DOM might be: `<div>Hello World!</div>`

In looking for a link to the docs on this I noted a couple things that may make all this moot, unfortunately.  Angular has [deprecated the `replace` flag](https://docs.angularjs.org/guide/migration) and [dropped support for IE8](https://docs.angularjs.org/guide/ie) as of Angular 1.3.  Given this, I think it makes best sense for ngToast to follow suit.

If we get further requests for IE8 I'll point them to your fork.  Thanks for using ngToast and your work here.

**Comment by tameraydin** [comment]
Hi @eknowles, sorry for my late reply...

I think switching to attributes not something drastic, so we can apply that. But I didn't get how using $sce helps on IE8? -and regardless that, wouldn't be better to leave it to the developer, i mean if you want to support IE8, message content should be passed as trusted via $sce?-

and I am not sure if we should drop the 1.4 support on package.json, maybe better just to leave as it is and if someone wants to support IE8 simply would use lower than 1.4.

If it still works with these changes -and of course if you have time to do it-, I can merge it.

Thanks a lot!

**Pull request closed without merging**
